name = "BayesianRegressionModels"
uuid = "cdd3e328-398d-47a6-a87b-6047aaf4b4bc"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com>"]
version = "0.2.1"

[deps]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StanBlocks = "2e771a56-c23a-4e0b-9282-20c2e37157e9"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
AlgebraOfVega = "a2420894-485a-4f42-a4fc-c4323ec6fb2b"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
NLMEEstimation = "93620da2-aa34-4028-9135-3a6a776ddbc2"
ReactiveKernels = "78e9f072-d36b-4c73-b7a3-751b0eb26cf9"
ReactiveKernelsPPL = "e266ea2a-6817-46cd-8bec-6238f0035f44"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
WarmupHMC = "60658175-6863-4866-a322-ab51a11c0cfe"

[extensions]
BayesianRegressionModelsAlgebraOfVegaExt = "AlgebraOfVega"
BayesianRegressionModelsNLMEEstimationExt = "NLMEEstimation"
BayesianRegressionModelsReactiveKernelsExt = ["ReactiveKernels", "ReactiveKernelsPPL"]
BayesianRegressionModelsTuringExt = "Turing"
BayesianRegressionModelsTuringWarmupHMCExt = ["Turing", "WarmupHMC"]
BayesianRegressionModelsWarmupHMCEnzymeExt = ["WarmupHMC", "Enzyme"]
BayesianRegressionModelsWarmupHMCExt = "WarmupHMC"

[compat]
BridgeStan = "2.9"
AlgebraOfVega = "0.2"
Enzyme = "0.13"
NLMEEstimation = "0.1"
ReactiveKernels = "0.1"
ReactiveKernelsPPL = "0.1"
RuntimeGeneratedFunctions = "0.5"
Turing = "0.46"
WarmupHMC = "0.2"
julia = "1.10"

