name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - ns/devibe
    tags: '*'
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git for private repos
        run: git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: |
          git clone https://github.com/nsiccha/DynamicObjects.jl.git
          git clone https://github.com/nsiccha/HTMX.jl.git
          git clone https://github.com/nsiccha/HTMXObjects.jl.git
          git clone https://github.com/nsiccha/ReactiveObjects.jl.git
          git clone https://github.com/nsiccha/ReactiveHMC.jl.git
          git clone https://github.com/nsiccha/StanBlocks.jl.git
          git clone https://github.com/nsiccha/Treebars.jl.git
          git clone https://github.com/nsiccha/WarmupHMC.jl.git
          julia --project=docs -e 'using Pkg; Pkg.develop([
            PackageSpec(path=pwd()),
            PackageSpec(path="DynamicObjects.jl"),
            PackageSpec(path="HTMX.jl"),
            PackageSpec(path="HTMXObjects.jl"),
            PackageSpec(path="ReactiveObjects.jl"),
            PackageSpec(path="ReactiveHMC.jl"),
            PackageSpec(path="StanBlocks.jl"),
            PackageSpec(path="Treebars.jl"),
            PackageSpec(path="WarmupHMC.jl"),
          ]); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/make.jl
